# Generated by Django 5.0.6 on 2024-06-09 19:40

import ckeditor.fields
import django.db.models.deletion
import flowerwall.models
import tools.views
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowerWall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بروزرسانی')),
                ('title', models.CharField(max_length=225, verbose_name='عنوان تجربه')),
                ('image', models.ImageField(upload_to=flowerwall.models.upload_image_path, validators=[tools.views.validate_image_extension], verbose_name='عکس کاور')),
                ('content', ckeditor.fields.RichTextField(null=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'FlowerWall',
                'verbose_name_plural': 'Flower Walls',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date:')),
                ('image', models.ImageField(blank=True, null=True, upload_to=flowerwall.models.upload_image_path, validators=[tools.views.validate_image_extension], verbose_name='Image:')),
                ('flowerwall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowerwall.flowerwall', verbose_name='flowerwall:')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Gallery Flower Wall',
            },
        ),
    ]
