# Generated by Django 5.0.6 on 2024-06-09 20:08

import flowerwall.models
import tools.views
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerwall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowerwall',
            name='image',
            field=models.ImageField(upload_to=flowerwall.models.upload_image_path, validators=[tools.views.validate_image_extension], verbose_name='Cover Image:'),
        ),
        migrations.AlterField(
            model_name='flowerwall',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='flowerwall',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date:'),
        ),
        migrations.AlterField(
            model_name='flowerwall',
            name='title',
            field=models.CharField(max_length=225, verbose_name='Title:'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=flowerwall.models.upload_image_path, validators=[tools.views.validate_image_extension], verbose_name='Gallery Image:'),
        ),
    ]
