# Generated by Django 5.0.6 on 2024-06-10 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerwall', '0002_alter_flowerwall_image_alter_flowerwall_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowerwall',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
