# Generated by Django 5.0.6 on 2024-06-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerwall', '0003_alter_flowerwall_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowerwall',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
