# Generated by Django 5.0.6 on 2024-06-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerwall', '0005_flowerwall_code_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowerwall',
            name='code',
            field=models.IntegerField(unique=True, verbose_name='Code:'),
        ),
    ]
