# Generated by Django 5.0.6 on 2024-06-10 18:08

import flowerwall.models
import tools.views
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerwall', '0006_alter_flowerwall_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowerwall',
            name='image',
            field=models.ImageField(help_text='resulotion(600*800)', upload_to=flowerwall.models.upload_image_path, validators=[tools.views.validate_image_extension], verbose_name='Cover Image:'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, help_text='resulotion(600*800)', null=True, upload_to=flowerwall.models.upload_image_gallery_path, validators=[tools.views.validate_image_extension], verbose_name='Gallery Image:'),
        ),
    ]
