# Generated by Django 5.0.6 on 2024-06-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date:')),
                ('name', models.CharField(max_length=100, verbose_name='Name:')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone:')),
                ('email', models.EmailField(max_length=100, verbose_name='Email:')),
                ('subject', models.CharField(max_length=200, verbose_name='عنوان پیام')),
                ('text', models.TextField(verbose_name='متن پیام')),
                ('is_read', models.BooleanField(verbose_name='has been read')),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'contact users',
            },
        ),
    ]
