# Generated by Django 5.0.6 on 2024-06-10 18:08

import promotion.models
import tools.views
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date:')),
                ('subtitle', models.CharField(max_length=225, verbose_name='Subtitle:')),
                ('title', models.CharField(max_length=225, verbose_name='Title:')),
                ('detail', models.TextField(verbose_name='Detail:')),
                ('subtitle_sec', models.CharField(max_length=225, verbose_name='Subtitle Second:')),
                ('title_sec', models.CharField(max_length=225, verbose_name='Title Second:')),
                ('detail_sec', models.TextField(verbose_name='Detail Second:')),
                ('image', models.ImageField(help_text='resulotion(1920*1000)', upload_to=promotion.models.upload_path, validators=[tools.views.validate_image_extension], verbose_name='Cover Image:')),
                ('video', models.FileField(help_text='resulotion(16*9 or 1080*1920)', upload_to=promotion.models.upload_path, validators=[tools.views.validate_video_extension], verbose_name='Video:')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Flower Walls',
            },
        ),
    ]
