# Generated by Django 5.0.6 on 2024-06-05 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_remove_settingssite_background_profile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settingssite',
            options={'verbose_name': 'settings', 'verbose_name_plural': 'settings website'},
        ),
    ]
