# Generated by Django 5.0.6 on 2024-06-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_alter_settingssite_location_maps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingssite',
            name='location_maps',
            field=models.CharField(blank=True, max_length=600, verbose_name='Location Maps:'),
        ),
    ]
